### ISSUE TITLE
Horizontal issue for chart

### ISSUE THREAD

**Issue by suniltayal** [MaTeMaTuK/gantt-task-react#115]
Hi @MaTeMaTuK 

I am using gantt chart with unlimited height. when I have too much data, then scrollbar is getting set at the bottom of the element.
I would like to show  horizontal scrollbar at the bottom of screen, not at the bottom of element.

Any thought on this.

Thank you,

**Comment by lordphnx** [comment]
Quick local fix for me, just add a little bit of CSS
```css
._2k9Ys{
    position: fixed;
    bottom: 0;
}
```
